### ISSUE TITLE
Purge useless css in final bundle?

### ISSUE THREAD

**Issue by frederikhors** [svelte-add/tailwindcss#28]
If I add for example:

`@import 'animate.css/animate'`

to `app.postcss` it doesn't purge useless code in final .css after `npm run build`.

Is it right or wrong?

**Comment by babichjacob** [comment]
That is right. Change your Tailwind purge mode to `all` for non-Tailwind CSS to be purged too.

**Comment by frederikhors** [comment]
It doesn't work either.

**Comment by babichjacob** [comment]
Got a repository?

**Comment by frederikhors** [comment]
Yep: https://github.com/frederikhors/protobuf-ts-issue-94/tree/add-tailwind

**Comment by babichjacob** [comment]
> 
> 
> That is right. Change your Tailwind purge mode to `all` for non-Tailwind CSS to be purged too.

This is all that's left from `animate.css` after following those instructions:
```css
/*!
 * animate.css - https://animate.style/
 * Version - 4.1.1
 * Licensed under the MIT license - http://opensource.org/licenses/MIT
 *
 * Copyright (c) 2020 Animate.css
 */:root{--animate-duration:1s;--animate-delay:1s;--animate-repeat:1}
```

where the full Tailwind config is
```js
const { tailwindExtractor } = require("tailwindcss/lib/lib/purgeUnusedStyles");

module.exports = {
	mode: "aot",
	purge: {
		content: [
			"./src/**/*.{html,js,svelte,ts}",
		],
		mode: "all",
		options: {
			defaultExtractor: (content) => [
				// If this stops working, please open an issue at https://github.com/svelte-add/tailwindcss/issues rather than bothering Tailwind Labs about it
				...tailwindExtractor(content),
				// Match Svelte class: directives (https://github.com/tailwindlabs/tailwindcss/discussions/1731)
				...[...content.matchAll(/(?:class:)*([\w\d-/:%.]+)/gm)].map(([_match, group, ..._rest]) => group),
			],
			keyframes: true,
		},
	},
	theme: {
		extend: {},
	},
	variants: {
		extend: {},
	},
	plugins: [],
};
```

**Comment by frederikhors** [comment]
With my reproduction (which has the same `tailwind.config.js` as you) the final css bundle is:

<details>
 <summary>Final CSS bundle</summary>

```css
#svelte-announcer.svelte-1y31lbn{position:absolute;left:0;top:0;clip:rect(0 0 0 0);-webkit-clip-path:inset(50%);clip-path:inset(50%);overflow:hidden;white-space:nowrap;width:1px;height:1px}/*! tailwindcss v2.1.1 | MIT License | https://tailwindcss.com*//*! modern-normalize v1.0.0 | MIT License | https://github.com/sindresorhus/modern-normalize */:root{-moz-tab-size:4;-o-tab-size:4;tab-size:4}html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji}hr{height:0;color:inherit}abbr[title]{-webkit-text-decoration:underline dotted;text-decoration:underline dotted}b,strong{font-weight:bolder}code,kbd,pre,samp{font-family:ui-monospace,SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;font-size:1em}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}sub{bottom:-.25em}sup{top:-.5em}table{text-indent:0;border-color:inherit}button,input,optgroup,select,textarea{font-family:inherit;font-size:100%;line-height:1.15;margin:0}button,select{text-transform:none}button{-webkit-appearance:button}legend{padding:0}progress{vertical-align:baseline}summary{display:list-item}blockquote,dd,dl,figure,h1,h2,h3,h4,h5,h6,hr,p,pre{margin:0}button{background-color:transparent;background-image:none}button:focus{outline:1px dotted;outline:5px auto -webkit-focus-ring-color}fieldset,ol,ul{margin:0;padding:0}ol,ul{list-style:none}html{font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;line-height:1.5}body{font-family:inherit;line-height:inherit}*,:after,:before{box-sizing:border-box;border:0 solid #e5e7eb}hr{border-top-width:1px}img{border-style:solid}textarea{resize:vertical}input::-moz-placeholder,textarea::-moz-placeholder{opacity:1;color:#9ca3af}input:-ms-input-placeholder,textarea:-ms-input-placeholder{opacity:1;color:#9ca3af}input::placeholder,textarea::placeholder{opacity:1;color:#9ca3af}button{cursor:pointer}table{border-collapse:collapse}h1,h2,h3,h4,h5,h6{font-size:inherit;font-weight:inherit}a{color:inherit;text-decoration:inherit}button,input,optgroup,select,textarea{padding:0;line-height:inherit;color:inherit}code,kbd,pre,samp{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace}audio,canvas,embed,iframe,img,object,svg,video{display:block;vertical-align:middle}img,video{max-width:100%;height:auto}.bg-red-500{--tw-bg-opacity:1;background-color:rgba(239,68,68,var(--tw-bg-opacity))}.bg-opacity-10{--tw-bg-opacity:0.1}.bg-opacity-20{--tw-bg-opacity:0.2}.border-opacity-100{--tw-border-opacity:1}.rounded-full{border-radius:9999px}.border{border-width:1px}.table{display:table}.font-thin{font-weight:100}.text-6xl{font-size:3.75rem;line-height:1}.leading-tight{line-height:1.25}.leading-snug{line-height:1.375}.my-8{margin-top:2rem;margin-bottom:2rem}.my-16{margin-top:4rem;margin-bottom:4rem}.mx-auto{margin-left:auto;margin-right:auto}.max-w-none{max-width:none}.max-w-xs{max-width:20rem}.outline-none{outline:2px solid transparent;outline-offset:2px}.p-4{padding:1rem}.py-4{padding-top:1rem;padding-bottom:1rem}.px-8{padding-left:2rem;padding-right:2rem}*{--tw-shadow:0 0 transparent;--tw-ring-inset:var(--tw-empty, );/*!*//*!*/--tw-ring-offset-width:0px;--tw-ring-offset-color:#fff;--tw-ring-color:rgba(59,130,246,0.5);--tw-ring-offset-shadow:0 0 transparent;--tw-ring-shadow:0 0 transparent}.text-center{text-align:center}.text-red-500{--tw-text-opacity:1;color:rgba(239,68,68,var(--tw-text-opacity))}.text-red-600{--tw-text-opacity:1;color:rgba(220,38,38,var(--tw-text-opacity))}.text-blue-600{--tw-text-opacity:1;color:rgba(37,99,235,var(--tw-text-opacity))}.uppercase{text-transform:uppercase}.underline{text-decoration:underline}.tabular-nums{--tw-ordinal:var(--tw-empty, );/*!*//*!*/--tw-slashed-zero:var(--tw-empty, );/*!*//*!*/--tw-numeric-figure:var(--tw-empty, );/*!*//*!*/--tw-numeric-spacing:var(--tw-empty, );/*!*//*!*/--tw-numeric-fraction:var(--tw-empty, );/*!*//*!*/font-variant-numeric:var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction);--tw-numeric-spacing:tabular-nums}.w-48{width:12rem}/*!
 * animate.css - https://animate.style/
 * Version - 4.1.1
 * Licensed under the MIT license - http://opensource.org/licenses/MIT
 *
 * Copyright (c) 2020 Animate.css
 */:root{--animate-duration:1s;--animate-delay:1s;--animate-repeat:1}.animate__animated{-webkit-animation-duration:1s;animation-duration:1s;-webkit-animation-duration:var(--animate-duration);animation-duration:var(--animate-duration);-webkit-animation-fill-mode:both;animation-fill-mode:both}.animate__animated.animate__infinite{-webkit-animation-iteration-count:infinite;animation-iteration-count:infinite}.animate__animated.animate__repeat-1{-webkit-animation-iteration-count:1;animation-iteration-count:1;-webkit-animation-iteration-count:var(--animate-repeat);animation-iteration-count:var(--animate-repeat)}.animate__animated.animate__repeat-2{-webkit-animation-iteration-count:2;animation-iteration-count:2;-webkit-animation-iteration-count:calc(var(--animate-repeat)*2);animation-iteration-count:calc(var(--animate-repeat)*2)}.animate__animated.animate__repeat-3{-webkit-animation-iteration-count:3;animation-iteration-count:3;-webkit-animation-iteration-count:calc(var(--animate-repeat)*3);animation-iteration-count:calc(var(--animate-repeat)*3)}.animate__animated.animate__delay-1s{-webkit-animation-delay:1s;animation-delay:1s;-webkit-animation-delay:var(--animate-delay);animation-delay:var(--animate-delay)}.animate__animated.animate__delay-2s{-webkit-animation-delay:2s;animation-delay:2s;-webkit-animation-delay:calc(var(--animate-delay)*2);animation-delay:calc(var(--animate-delay)*2)}.animate__animated.animate__delay-3s{-webkit-animation-delay:3s;animation-delay:3s;-webkit-animation-delay:calc(var(--animate-delay)*3);animation-delay:calc(var(--animate-delay)*3)}.animate__animated.animate__delay-4s{-webkit-animation-delay:4s;animation-delay:4s;-webkit-animation-delay:calc(var(--animate-delay)*4);animation-delay:calc(var(--animate-delay)*4)}.animate__animated.animate__delay-5s{-webkit-animation-delay:5s;animation-delay:5s;-webkit-animation-delay:calc(var(--animate-delay)*5);animation-delay:calc(var(--animate-delay)*5)}.animate__animated.animate__faster{-webkit-animation-duration:.5s;animation-duration:.5s;-webkit-animation-duration:calc(var(--animate-duration)/2);animation-duration:calc(var(--animate-duration)/2)}.animate__animated.animate__fast{-webkit-animation-duration:.8s;animation-duration:.8s;-webkit-animation-duration:calc(var(--animate-duration)*.8);animation-duration:calc(var(--animate-duration)*.8)}.animate__animated.animate__slow{-webkit-animation-duration:2s;animation-duration:2s;-webkit-animation-duration:calc(var(--animate-duration)*2);animation-duration:calc(var(--animate-duration)*2)}.animate__animated.animate__slower{-webkit-animation-duration:3s;animation-duration:3s;-webkit-animation-duration:calc(var(--animate-duration)*3);animation-duration:calc(var(--animate-duration)*3)}@media (prefers-reduced-motion:reduce),print{.animate__animated{-webkit-animation-duration:1ms!important;animation-duration:1ms!important;transition-duration:1ms!important;-webkit-animation-iteration-count:1!important;animation-iteration-count:1!important}.animate__animated[class*=Out]{opacity:0}}.animate__bounce{-webkit-animation-name:bounce;animation-name:bounce;transform-origin:center bottom}.animate__flash{-webkit-animation-name:flash;animation-name:flash}.animate__pulse{-webkit-animation-name:pulse;animation-name:pulse;-webkit-animation-timing-function:ease-in-out;animation-timing-function:ease-in-out}.animate__rubberBand{-webkit-animation-name:rubberBand;animation-name:rubberBand}.animate__shakeX{-webkit-animation-name:shakeX;animation-name:shakeX}.animate__shakeY{-webkit-animation-name:shakeY;animation-name:shakeY}.animate__headShake{-webkit-animation-timing-function:ease-in-out;animation-timing-function:ease-in-out;-webkit-animation-name:headShake;animation-name:headShake}.animate__swing{transform-origin:top center;-webkit-animation-name:swing;animation-name:swing}.animate__tada{-webkit-animation-name:tada;animation-name:tada}.animate__wobble{-webkit-animation-name:wobble;animation-name:wobble}.animate__jello{-webkit-animation-name:jello;animation-name:jello;transform-origin:center}.animate__heartBeat{-webkit-animation-name:heartBeat;animation-name:heartBeat;-webkit-animation-duration:1.3s;animation-duration:1.3s;-webkit-animation-duration:calc(var(--animate-duration)*1.3);animation-duration:calc(var(--animate-duration)*1.3);-webkit-animation-timing-function:ease-in-out;animation-timing-function:ease-in-out}.animate__backInDown{-webkit-animation-name:backInDown;animation-name:backInDown}.animate__backInLeft{-webkit-animation-name:backInLeft;animation-name:backInLeft}.animate__backInRight{-webkit-animation-name:backInRight;animation-name:backInRight}.animate__backInUp{-webkit-animation-name:backInUp;animation-name:backInUp}.animate__backOutDown{-webkit-animation-name:backOutDown;animation-name:backOutDown}.animate__backOutLeft{-webkit-animation-name:backOutLeft;animation-name:backOutLeft}.animate__backOutRight{-webkit-animation-name:backOutRight;animation-name:backOutRight}.animate__backOutUp{-webkit-animation-name:backOutUp;animation-name:backOutUp}.animate__bounceIn{-webkit-animation-duration:.75s;animation-duration:.75s;-webkit-animation-duration:calc(var(--animate-duration)*.75);animation-duration:calc(var(--animate-duration)*.75);-webkit-animation-name:bounceIn;animation-name:bounceIn}.animate__bounceInDown{-webkit-animation-name:bounceInDown;animation-name:bounceInDown}.animate__bounceInLeft{-webkit-animation-name:bounceInLeft;animation-name:bounceInLeft}.animate__bounceInRight{-webkit-animation-name:bounceInRight;animation-name:bounceInRight}.animate__bounceInUp{-webkit-animation-name:bounceInUp;animation-name:bounceInUp}.animate__bounceOut{-webkit-animation-duration:.75s;animation-duration:.75s;-webkit-animation-duration:calc(var(--animate-duration)*.75);animation-duration:calc(var(--animate-duration)*.75);-webkit-animation-name:bounceOut;animation-name:bounceOut}.animate__bounceOutDown{-webkit-animation-name:bounceOutDown;animation-name:bounceOutDown}.animate__bounceOutLeft{-webkit-animation-name:bounceOutLeft;animation-name:bounceOutLeft}.animate__bounceOutRight{-webkit-animation-name:bounceOutRight;animation-name:bounceOutRight}.animate__bounceOutUp{-webkit-animation-name:bounceOutUp;animation-name:bounceOutUp}.animate__fadeIn{-webkit-animation-name:fadeIn;animation-name:fadeIn}.animate__fadeInDown{-webkit-animation-name:fadeInDown;animation-name:fadeInDown}.animate__fadeInDownBig{-webkit-animation-name:fadeInDownBig;animation-name:fadeInDownBig}.animate__fadeInLeft{-webkit-animation-name:fadeInLeft;animation-name:fadeInLeft}.animate__fadeInLeftBig{-webkit-animation-name:fadeInLeftBig;animation-name:fadeInLeftBig}.animate__fadeInRight{-webkit-animation-name:fadeInRight;animation-name:fadeInRight}.animate__fadeInRightBig{-webkit-animation-name:fadeInRightBig;animation-name:fadeInRightBig}.animate__fadeInUp{-webkit-animation-name:fadeInUp;animation-name:fadeInUp}.animate__fadeInUpBig{-webkit-animation-name:fadeInUpBig;animation-name:fadeInUpBig}.animate__fadeInTopLeft{-webkit-animation-name:fadeInTopLeft;animation-name:fadeInTopLeft}.animate__fadeInTopRight{-webkit-animation-name:fadeInTopRight;animation-name:fadeInTopRight}.animate__fadeInBottomLeft{-webkit-animation-name:fadeInBottomLeft;animation-name:fadeInBottomLeft}.animate__fadeInBottomRight{-webkit-animation-name:fadeInBottomRight;animation-name:fadeInBottomRight}.animate__fadeOut{-webkit-animation-name:fadeOut;animation-name:fadeOut}.animate__fadeOutDown{-webkit-animation-name:fadeOutDown;animation-name:fadeOutDown}.animate__fadeOutDownBig{-webkit-animation-name:fadeOutDownBig;animation-name:fadeOutDownBig}.animate__fadeOutLeft{-webkit-animation-name:fadeOutLeft;animation-name:fadeOutLeft}.animate__fadeOutLeftBig{-webkit-animation-name:fadeOutLeftBig;animation-name:fadeOutLeftBig}.animate__fadeOutRight{-webkit-animation-name:fadeOutRight;animation-name:fadeOutRight}.animate__fadeOutRightBig{-webkit-animation-name:fadeOutRightBig;animation-name:fadeOutRightBig}.animate__fadeOutUp{-webkit-animation-name:fadeOutUp;animation-name:fadeOutUp}.animate__fadeOutUpBig{-webkit-animation-name:fadeOutUpBig;animation-name:fadeOutUpBig}.animate__fadeOutTopLeft{-webkit-animation-name:fadeOutTopLeft;animation-name:fadeOutTopLeft}.animate__fadeOutTopRight{-webkit-animation-name:fadeOutTopRight;animation-name:fadeOutTopRight}.animate__fadeOutBottomRight{-webkit-animation-name:fadeOutBottomRight;animation-name:fadeOutBottomRight}.animate__fadeOutBottomLeft{-webkit-animation-name:fadeOutBottomLeft;animation-name:fadeOutBottomLeft}.animate__animated.animate__flip{-webkit-backface-visibility:visible;backface-visibility:visible;-webkit-animation-name:flip;animation-name:flip}.animate__flipInX{-webkit-animation-name:flipInX;animation-name:flipInX}.animate__flipInX,.animate__flipInY{-webkit-backface-visibility:visible!important;backface-visibility:visible!important}.animate__flipInY{-webkit-animation-name:flipInY;animation-name:flipInY}.animate__flipOutX{-webkit-animation-name:flipOutX;animation-name:flipOutX}.animate__flipOutX,.animate__flipOutY{-webkit-animation-duration:.75s;animation-duration:.75s;-webkit-animation-duration:calc(var(--animate-duration)*.75);animation-duration:calc(var(--animate-duration)*.75);-webkit-backface-visibility:visible!important;backface-visibility:visible!important}.animate__flipOutY{-webkit-animation-name:flipOutY;animation-name:flipOutY}.animate__lightSpeedInRight{-webkit-animation-name:lightSpeedInRight;animation-name:lightSpeedInRight;-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}.animate__lightSpeedInLeft{-webkit-animation-name:lightSpeedInLeft;animation-name:lightSpeedInLeft;-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}.animate__lightSpeedOutRight{-webkit-animation-name:lightSpeedOutRight;animation-name:lightSpeedOutRight;-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}.animate__lightSpeedOutLeft{-webkit-animation-name:lightSpeedOutLeft;animation-name:lightSpeedOutLeft;-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}.animate__rotateIn{-webkit-animation-name:rotateIn;animation-name:rotateIn;transform-origin:center}.animate__rotateInDownLeft{-webkit-animation-name:rotateInDownLeft;animation-name:rotateInDownLeft;transform-origin:left bottom}.animate__rotateInDownRight{-webkit-animation-name:rotateInDownRight;animation-name:rotateInDownRight;transform-origin:right bottom}.animate__rotateInUpLeft{-webkit-animation-name:rotateInUpLeft;animation-name:rotateInUpLeft;transform-origin:left bottom}.animate__rotateInUpRight{-webkit-animation-name:rotateInUpRight;animation-name:rotateInUpRight;transform-origin:right bottom}.animate__rotateOut{-webkit-animation-name:rotateOut;animation-name:rotateOut;transform-origin:center}.animate__rotateOutDownLeft{-webkit-animation-name:rotateOutDownLeft;animation-name:rotateOutDownLeft;transform-origin:left bottom}.animate__rotateOutDownRight{-webkit-animation-name:rotateOutDownRight;animation-name:rotateOutDownRight;transform-origin:right bottom}.animate__rotateOutUpLeft{-webkit-animation-name:rotateOutUpLeft;animation-name:rotateOutUpLeft;transform-origin:left bottom}.animate__rotateOutUpRight{-webkit-animation-name:rotateOutUpRight;animation-name:rotateOutUpRight;transform-origin:right bottom}.animate__hinge{-webkit-animation-duration:2s;animation-duration:2s;-webkit-animation-duration:calc(var(--animate-duration)*2);animation-duration:calc(var(--animate-duration)*2);-webkit-animation-name:hinge;animation-name:hinge;transform-origin:top left}.animate__jackInTheBox{-webkit-animation-name:jackInTheBox;animation-name:jackInTheBox}.animate__rollIn{-webkit-animation-name:rollIn;animation-name:rollIn}.animate__rollOut{-webkit-animation-name:rollOut;animation-name:rollOut}.animate__zoomIn{-webkit-animation-name:zoomIn;animation-name:zoomIn}.animate__zoomInDown{-webkit-animation-name:zoomInDown;animation-name:zoomInDown}.animate__zoomInLeft{-webkit-animation-name:zoomInLeft;animation-name:zoomInLeft}.animate__zoomInRight{-webkit-animation-name:zoomInRight;animation-name:zoomInRight}.animate__zoomInUp{-webkit-animation-name:zoomInUp;animation-name:zoomInUp}.animate__zoomOut{-webkit-animation-name:zoomOut;animation-name:zoomOut}.animate__zoomOutDown{-webkit-animation-name:zoomOutDown;animation-name:zoomOutDown;transform-origin:center bottom}.animate__zoomOutLeft{-webkit-animation-name:zoomOutLeft;animation-name:zoomOutLeft;transform-origin:left center}.animate__zoomOutRight{-webkit-animation-name:zoomOutRight;animation-name:zoomOutRight;transform-origin:right center}.animate__zoomOutUp{-webkit-animation-name:zoomOutUp;animation-name:zoomOutUp;transform-origin:center bottom}.animate__slideInDown{-webkit-animation-name:slideInDown;animation-name:slideInDown}.animate__slideInLeft{-webkit-animation-name:slideInLeft;animation-name:slideInLeft}.animate__slideInRight{-webkit-animation-name:slideInRight;animation-name:slideInRight}.animate__slideInUp{-webkit-animation-name:slideInUp;animation-name:slideInUp}.animate__slideOutDown{-webkit-animation-name:slideOutDown;animation-name:slideOutDown}.animate__slideOutLeft{-webkit-animation-name:slideOutLeft;animation-name:slideOutLeft}.animate__slideOutRight{-webkit-animation-name:slideOutRight;animation-name:slideOutRight}.animate__slideOutUp{-webkit-animation-name:slideOutUp;animation-name:slideOutUp}body{background-color:red}
```

 ...this is hidden, collapsable content...
</details>

**Comment by frederikhors** [comment]
Maybe I'm importing it wrong here?

- app.postcss:

```css
@import 'tailwind.postcss';

@import 'animate.css/animate';

body {
	background-color: red;
}
```
