### ISSUE TITLE
cannot override applied classes 

### ISSUE THREAD

**Issue by opensas** [svelte-add/tailwindcss#38]
If I enter the following in the index.svelte file:

```svelte
<button class="btn-red text-green-400">
  Click me<br />(from index.svelte, components layer)
</button>

<style>
  @layer components {
    .btn-red {
      @apply py-2 px-4 bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-400 focus:ring-opacity-75;
    }
  }
</style>
```

The .btn-red clases are not applied, the text-green-400 overrides them all.

On the other hand, if I do the same on the app.postcss file it works as expected.

Complete example:

```svelte
<!-- index.svelte -->

<button class="btn-red text-green-400">
  Click me<br />
</button>

<button class="btn-indigo text-green-400">
  Click me<br />
</button>

<style>
  @layer components {
    .btn-red {
      @apply py-2 px-4 bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-400 focus:ring-opacity-75;
    }
  }
</style>
```

```postcss
/* app.postcss */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  .btn-indigo {
    @apply py-2 px-4 bg-indigo-500 text-white font-semibold rounded-lg shadow-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-opacity-75;
  }
}
```

output:

![image](https://user-images.githubusercontent.com/481687/116001009-daedec80-a5c8-11eb-8c9a-0de9ff795fca.png)

**Comment by babichjacob** [comment]
Don't wrap it in a components layer -- you're already in a component file!

**Comment by opensas** [comment]
yes, that's the first thing I tried, I asked at SO and was told that I have to inlude it in a components layer:

> This is a property of CSS, not tailwind. The specificity of your selector is greater than that of tailwinds utility classes. You can use the @layer directive to fix this by defining your class

from [tailwind docs](https://tailwindcss.com/docs/functions-and-directives#layer):

> Tailwind will automatically move any CSS within a @layer directive to the same place as the corresponding @tailwind rule, so you don't have to worry as much about authoring your CSS in a specific order to avoid specificity issues.

from [SO question](https://stackoverflow.com/questions/67244926/how-to-override-apply-directives-in-tailwindcss)

If I don't include it in a components layer I can't override the settings.

here's the example:

```svelte
<!-- index.svelte -->

<button class="btn-red text-green-400">
	Click me<br />
</button>

<button class="btn-indigo text-green-400">
	Click me<br />
</button>

<button class="btn-blue text-green-400">
	Click me<br />
</button>

<style>
	.btn-blue {
		@apply py-2 px-4 bg-blue-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75;
	}
	@layer components {
		.btn-red {
			@apply py-2 px-4 bg-red-500 text-white font-semibold rounded-lg shadow-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-400 focus:ring-opacity-75;
		}
	}
</style>
```

and the output

![image](https://user-images.githubusercontent.com/481687/116006897-8f950780-a5e3-11eb-8410-a04271ce0328.png)

The only way I could make it work is from app.postcss inside a components layer. I guess it should work the same from a component.

**Comment by babichjacob** [comment]
Last I checked, Svelte style encapsulation adds an extra class to `.btn-red` (something along the lines of `.btn-red.s-d12a3e`) that causes "component classes" to have higher specificity than an `@layer` directive can solve.

Additionally, it's possible there are purge issues (I only tested in JIT) because `@layer` causes the rules inside it to be subject to purging; they should be preserved though because the paths are included...).

**Comment by opensas** [comment]
I tried to debug a little bit the issue

Apperantly the clases generated from the index.svelte componente go to a `.svelte/output/client/_app/assets/pages/index.svelte-e3097bc8.css` frile like this:

```css

.btn-blue.svelte-kwltzd {
	--tw-bg-opacity: 1;
	background-color: rgba(59, 130, 246, var(--tw-bg-opacity))
}

.btn-blue.svelte-kwltzd:hover {
	--tw-bg-opacity: 1;
	background-color: rgba(29, 78, 216, var(--tw-bg-opacity))
}
[...]
.btn-red.svelte-kwltzd {
	--tw-bg-opacity: 1;
	background-color: rgba(239, 68, 68, var(--tw-bg-opacity))
}

.btn-red.svelte-kwltzd:hover {
	--tw-bg-opacity: 1;
	background-color: rgba(185, 28, 28, var(--tw-bg-opacity))
}
[...]
```

And the cases from app.postcss goes to `.svelte/output/client/_app/assets/pages/$layout.svelte-d9921e96.css'
right after several css reset settings and before several classes that seem to be tailwind utilities

```css
[...]
img,
video {
	height: auto;
	max-width: 100%
}

.btn-indigo {
	--tw-bg-opacity: 1;
	background-color: rgba(99, 102, 241, var(--tw-bg-opacity))
}

.btn-indigo:hover {
	--tw-bg-opacity: 1;
	background-color: rgba(67, 56, 202, var(--tw-bg-opacity))
}
[..]

.btn-indigo {
	--tw-text-opacity: 1;
	color: rgba(255, 255, 255, var(--tw-text-opacity))
}

.bg-red-500 {
	--tw-bg-opacity: 1;
	background-color: rgba(239, 68, 68, var(--tw-bg-opacity))
}

.bg-blue-500 {
	--tw-bg-opacity: 1;
	background-color: rgba(59, 130, 246, var(--tw-bg-opacity))
}

.hover\:bg-red-700:hover {
	--tw-bg-opacity: 1;
	background-color: rgba(185, 28, 28, var(--tw-bg-opacity))
}
```

I'm trying to understand why it works from the app.postcss file and not from the component, to see how it could be fixed

**Comment by babichjacob** [comment]
Svelte component styles are not added to the global stylesheet.


>  right after several css reset settings and before several classes that seem to be tailwind utilities
Correct, that's because the component layer is between the base layer (where the resets are) and the utilities layer.

**Comment by opensas** [comment]
Well, I guess Svelte' scoping css system is somehow messing with tailwind apply directive.

I don't know how to debug it, but all of the sudden I can't apply a class created with apply from app.postcss in the components (or base layer). It used to work but all of the sudden it stopped working.

It makes extracting common clases with @apply a trial an error process, where you have to just try what works and what doesn't

**Comment by opensas** [comment]
For example, right now I get:

```sh
✓ 45 modules transformed.
[vite-plugin-svelte] /home/sas/devel/apps/glas-it/apps/89transfers/src/89transfers-fe/src/lib/components/RatingStars.svelte:17:5: The `mb-p1` class does not exist. If `mb-p1` is a custom class, make sure it is defined within a `@layer` directive.
file: /home/sas/devel/apps/glas-it/apps/89transfers/src/89transfers-fe/src/lib/components/RatingStars.svelte
> /home/sas/devel/apps/glas-it/apps/89transfers/src/89transfers-fe/src/lib/components/RatingStars.svelte:17:5: The `mb-p1` class does not exist. If `mb-p1` is a custom class, make sure it is defined within a `@layer` directive.
CssSyntaxError: /home/sas/devel/apps/glas-it/apps/89transfers/src/89transfers-fe/src/lib/components/RatingStars.svelte:17:5: The `mb-p1` class does not exist. If `mb-p1` is a custom class, make sure it is defined within a `@layer` directive.
```

even thought I have this in my app.postcss

```css
@layer components {

  /* mobile type scale */
  .mb-h1 {
    font-size: 2.5rem;                  /* 40px */
    line-height: 3.625rem;              /* 58px */
    @apply font-serif font-bold
  }
[...]
````

It works ok on dev, and on production, I only get this error when building with a ` export const prerender = true;`

I'll try the same without jit, to see if that's the problem
